### ISSUE TITLE
Get example data for curve fitting.

### ISSUE THREAD

**Issue by Andresruizmarin** [Aruma27/Bioenterprise-Perkin-Elmer#1]

**Comment by oskarmora** [comment]
[example_data.txt](https://github.com/Aruma27/Bioenterprise-Perkin-Elmer/files/984210/example_data.txt)

Attached an example dataset for curve fitting.
Parameter columns: 
 - My Assay Readout 1 - Cell Number	
 - My Assay Readout 2 - DNA Signal	
 - My Assay Readout 3 - pHH3 Signal	
 - My Assay Readout 4 - Nuclear Area

Compound (identifier column): 
 - Compound-Name	

Compound concentration: 
 - Compound-Concentration
