### ISSUE TITLE
DXP File

### ISSUE THREAD

**Issue by Andresruizmarin** [Aruma27/Bioenterprise-Perkin-Elmer#2]
Get an example data for testing issues.

**Comment by oskarmora** [comment]
Example data shared in BOX:

https://perkinelmer.box.com/s/covuy54822vyrzb6cgh7y5y2dxtp9ykl

Let me know if you have problems accessing to it

**Comment by Andresruizmarin** [comment]
Thank you.

I already tested them and I had no problems using them.
